In [5]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [31]:
names_df = pd.read_csv('./sp500_companies.csv')
index = list(names_df['Symbol'].str.replace('.', '-').replace('FI', 'FISV'))
index.remove('WBA')
index.remove('IPG')
index.remove('K')
index.remove('PSKY')

## New Attempt with Trailing P/E

In [72]:
# retrieving all prices
dates = ['2025-12-30','2025-09-30', '2025-06-30', '2025-03-31', '2024-12-30']

price_data = {}
for x in index:
    ticker = yf.Ticker(x)
    prices = {}
    for d in dates:
        try:
            price = ticker.history(start=d,end=pd.to_datetime(d) + pd.Timedelta(days=1), interval="1d")['Close'].values[0]
            prices[d] = price
        except Exception as e:
            print(f"Skipping {x}: {e}")
            continue
    price_data[x] = prices

In [73]:
price_df = pd.DataFrame(price_data)
price_df

,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,WMB,WTW,WDAY,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
2025-12-30,161.169998,67.739998,125.146072,227.906326,270.000000,352.510010,215.339996,14.500000,110.800003,137.374466,...,60.160000,332.659973,216.929993,120.330002,74.190002,137.589996,152.179993,246.740005,90.790001,125.872520
2025-09-30,154.516052,73.013786,132.674973,228.047928,246.600006,352.750000,161.789993,12.994796,111.120308,128.121017,...,62.830055,344.497284,240.729996,128.004395,80.032280,147.084015,151.283585,297.160004,98.238876,145.192322
2025-06-30,150.891434,64.903046,134.123367,181.254974,297.402588,386.880005,141.899994,10.248904,104.343422,117.316322,...,61.769505,304.832947,240.000000,93.262520,67.053253,128.638397,146.769119,308.359985,90.746056,154.232361
2025-03-31,144.849670,64.366974,130.206833,202.719528,308.955109,383.529999,102.739998,11.886984,109.408638,116.045837,...,58.280930,335.096405,233.529999,82.924141,69.126686,118.415443,155.100906,282.559998,112.313057,162.288910
2024-12-30,126.737206,66.648193,110.144440,168.888351,347.528259,445.799988,122.440002,11.918039,100.756676,133.100540,...,52.349442,308.877319,262.000000,85.003288,64.916191,114.906883,130.984192,383.850006,104.369041,159.431503

In [18]:
earnings_data = {}
yearly_earnings_data = {}
for x in index:
    ticker = yf.Ticker(x)
    try:
        earnings = dict(ticker.quarterly_income_stmt.loc['Basic EPS'])
        yearly = dict(ticker.income_stmt.loc['Basic EPS'])
        earnings_data[x] = earnings
        yearly_earnings_data[x] = yearly

    except Exception as e:
        print(f"Skipping {x}: {e}")
        continue

In [ ]:
earnings_df = pd.DataFrame(earnings_data)
earnings_df.index = earnings_df.index.snap('QE')
earnings_df = earnings_df[earnings_df.index.year.isin([2024, 2025])].groupby(level=0).first().loc['2023-12-31':'2025-09-30']

preprocessed_earnings_df = earnings_df.loc['2024-12-31':'2025-09-30'].sort_index(ascending=False)
# .loc['2024-12-31':'2025-09-30'].sort_index(ascending=False)

In [27]:
yearly_earnings_df = pd.DataFrame(yearly_earnings_data)
yearly_earnings_df.index = yearly_earnings_df.index.snap('QE')
yearly_earnings_df = yearly_earnings_df[yearly_earnings_df.index.year.isin([2024,2025])].groupby(level=0).first().sort_index(ascending=False)
yearly_earnings_df

,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,WMB,WTW,WDAY,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
2025-12-31,6.05,NaN,3.751858,NaN,NaN,16.73,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09-30,NaN,NaN,NaN,NaN,12.29,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-31,7.58,3.627859,7.739225,2.423443,NaN,12.43,1.01,2.38,9.68,NaN,...,1.82,-0.96,1.98,4.56,3.44,3.67,5.28,10.25,4.45,5.47
2024-09-30,NaN,NaN,NaN,NaN,11.57,NaN,NaN,NaN,NaN,4.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
check_for_na = ['2025-09-30','2025-06-30', '2025-03-31', '2024-12-31']


for x in index:
    for i in check_for_na:
        if np.isnan(earnings_df[x].loc[i]):
            print(x, i)

ARE 2024-12-31
AEP 2024-12-31
AWK 2024-12-31
BRK-B 2024-12-31
XYZ 2024-12-31
CNP 2024-12-31
DTE 2024-12-31
EIX 2024-12-31
EVRG 2024-12-31
FE 2024-12-31
F 2024-12-31
GM 2024-12-31
LIN 2024-12-31
LYV 2024-12-31
LYB 2024-12-31
NI 2024-12-31
NOC 2024-12-31
NRG 2024-12-31
PCG 2024-12-31
PFG 2024-12-31
PGR 2024-12-31
PLD 2024-12-31
TMUS 2024-12-31
URI 2024-12-31
VST 2024-12-31
WSM 2024-12-31
WMB 2024-12-31
XYL 2024-12-31

In [ ]:
check_for_na = ['2025-09-30','2025-06-30', '2025-03-31', '2024-12-31']

for x in index:
    for i in check_for_na:
        if (np.isnan(earnings_df.loc[i, x])) and (i == '2025-09-30'):
            q_sum = sum(earnings_df[x].loc[check_for_na[1:]]) #sum of quarterly
            y_eps = yearly_earnings_df[x].loc['2025-09-30'] # yearly
            q_eps = y_eps - q_sum #quarterly eps
            earnings_df[x].loc[i] = q_eps
            # print(earnings_df.loc[i, x]) # to check for na
        elif (np.isnan(earnings_df.loc[i, x])) and (i == '2025-06-30'):
            q_sum = sum(earnings_df[x].loc[['2025-03-31', '2024-12-31', '2024-09-30']]) #sum of quarterly
            y_eps = yearly_earnings_df[x].loc['2025-06-30'] # yearly
            q_eps = y_eps - q_sum #quarterly eps
            earnings_df[x].loc[i] = q_eps

In [52]:
print(earnings_df.loc['2025-09-30', 'ATO'])

1.0700000000000003

In [ ]:
def eps_cleaning(x):
    if np.isnan(x).any():
        print(x.name)

In [69]:
preprocessed_earnings_df

,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,WMB,WTW,WDAY,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
2025-09-30,1.56,0.936868,0.945441,0.105242,2.27,4.18,0.76,0.89,3.09,1.53,...,0.53,3.12,0.95,0.86,0.88,0.93,1.42,1.98,1.17,1.63
2025-06-30,1.35,1.068190,1.022144,0.531005,3.52,3.95,0.54,-0.15,1.12,1.18,...,0.45,3.34,0.86,0.64,0.76,0.93,1.34,2.20,0.77,1.61
2025-03-31,2.05,0.945931,0.760000,0.728080,2.85,4.15,0.44,0.07,0.05,0.75,...,0.57,2.34,0.25,0.69,0.84,0.69,0.91,2.64,0.92,1.41
2024-12-31,1.34,0.752617,5.329451,-0.012463,3.64,3.81,0.30,0.79,3.44,1.12,...,NaN,12.32,0.35,2.56,0.81,NaN,1.51,3.17,1.20,1.29

In [79]:
quarters = ['2025-09-30','2025-06-30', '2025-03-31', '2024-12-31']
price_dates = ['2025-12-30','2025-09-30', '2025-06-30', '2025-03-31', '2024-12-30']

pe_ratio_data = {}
for x in index:
    dic = {}
    for q in quarters:
        if (np.isnan(earnings_df.loc[q, x])) and (q == quarters[-1]):
            eps_2024 = yearly_earnings_df.loc[q, x]
            price = price_df.loc[price_dates[-1], x]
            pe_ratio = price / eps_2024
        else:
            eps = earnings_df.loc[q, x]
            if q == quarters[-1]:
                price = price_df.loc[price_dates[-1], x]
            else:
                price = price_df.loc[q, x]
            if eps > 0:
                pe_ratio = price / (eps * 4)
            else:
                pe_ratio = 0
        dic[q] = pe_ratio
    pe_ratio_data[x] = dic

In [85]:
pe_df = pd.DataFrame(pe_ratio_data)

In [86]:
pe_df

,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,WMB,WTW,WDAY,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
2025-09-30,24.762188,19.483477,35.082827,541.722715,27.158591,21.097488,53.220393,3.650224,8.990316,20.934807,...,29.636819,27.603949,63.349999,37.210580,22.736443,39.538714,26.634434,37.520202,20.991213,22.268761
2025-06-30,27.942858,15.189958,32.804421,85.335813,21.122343,24.486076,65.694442,0.000000,23.290942,24.855153,...,34.316391,22.816837,69.767442,36.430672,22.056991,34.580214,27.382298,35.040907,29.463005,23.949124
2025-03-31,17.664594,17.011540,42.831195,69.607573,27.101325,23.104217,58.374999,42.453514,547.043190,38.681946,...,25.561811,35.800898,233.529999,30.044979,20.573418,42.904146,42.610139,26.757576,30.519852,28.774629
2024-12-31,23.645001,22.138815,5.166782,0.000000,23.868699,29.251968,102.033335,3.771531,7.322433,29.709942,...,28.763429,6.267803,187.142857,8.301102,20.035861,31.309777,21.686124,30.272083,21.743550,30.897578

In [89]:
pe_long = pe_df.stack().rename('pe_ratio').reset_index()
pe_long

         level_0 level_1    pe_ratio
0     2025-09-30     MMM   24.762188
1     2025-09-30     AOS   19.483477
2     2025-09-30     ABT   35.082827
3     2025-09-30    ABBV  541.722715
4     2025-09-30     ACN   27.158591
...          ...     ...         ...
1991  2024-12-31     XYL   31.309777
1992  2024-12-31     YUM   21.686124
1993  2024-12-31    ZBRA   30.272083
1994  2024-12-31     ZBH   21.743550
1995  2024-12-31     ZTS   30.897578

[1996 rows x 3 columns]

In [124]:
price_long = price_df.stack().rename('price').reset_index()

In [125]:
price_long

         level_0 level_1       price
0     2025-12-30     MMM  161.169998
1     2025-12-30     AOS   67.739998
2     2025-12-30     ABT  125.146072
3     2025-12-30    ABBV  227.906326
4     2025-12-30     ACN  270.000000
...          ...     ...         ...
2490  2024-12-30     XYL  114.906883
2491  2024-12-30     YUM  130.984192
2492  2024-12-30    ZBRA  383.850006
2493  2024-12-30     ZBH  104.369041
2494  2024-12-30     ZTS  159.431503

[2495 rows x 3 columns]

In [128]:
price_long['price_lag'] = price_long.groupby('level_1')['price'].shift(1)

In [129]:
price_long

         level_0 level_1       price   price_lag
0     2025-12-30     MMM  161.169998         NaN
1     2025-12-30     AOS   67.739998         NaN
2     2025-12-30     ABT  125.146072         NaN
3     2025-12-30    ABBV  227.906326         NaN
4     2025-12-30     ACN  270.000000         NaN
...          ...     ...         ...         ...
2490  2024-12-30     XYL  114.906883  118.415443
2491  2024-12-30     YUM  130.984192  155.100906
2492  2024-12-30    ZBRA  383.850006  282.559998
2493  2024-12-30     ZBH  104.369041  112.313057
2494  2024-12-30     ZTS  159.431503  162.288910

[2495 rows x 4 columns]

In [130]:
#remove all rows where level_0 is 2025-12-30 and replace 12-31 to 12-30 (align with prices)
price_long = price_long[price_long['level_0'] != '2025-12-30']

In [136]:
pe_long['level_0'] = pe_long['level_0'].str.replace('2024-12-31', '2024-12-30')
pe_long

         level_0 level_1    pe_ratio
0     2025-09-30     MMM   24.762188
1     2025-09-30     AOS   19.483477
2     2025-09-30     ABT   35.082827
3     2025-09-30    ABBV  541.722715
4     2025-09-30     ACN   27.158591
...          ...     ...         ...
1991  2024-12-30     XYL   31.309777
1992  2024-12-30     YUM   21.686124
1993  2024-12-30    ZBRA   30.272083
1994  2024-12-30     ZBH   21.743550
1995  2024-12-30     ZTS   30.897578

[1996 rows x 3 columns]

In [147]:
merged = pd.merge(pe_long, price_long)

In [148]:
merged = merged.rename(columns={'level_0': 'quarter_date', 'level_1': 'company'})

In [ ]:
merged.to_excel('')